spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres # 数据库地址
    username: java2  # 数据库用户名
    password: Java2  # 数据库密码
    driver-class-name: org.postgresql.Driver

  # Redis配置
  data:
    redis:
     host: localhost
     port: 6379
     password:  # 如果有密码，请在这里填写
     database: 0

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tEnZ1ZE7QNq1fbRp2RC
    accessKeySecret: SH0gtLOZfqCK2ctr4OAnzUiIft1zgE
    bucketName: big-event-isaac