spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres # 数据库地址
    username: zhangv1  # 数据库用户名
    password: Zwy20040430  # 数据库密码
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
     ddl-auto: update
      #  ddl-auto: create
    show-sql: true
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5t5kAim3zAD8axkEoaCA
    access-key-secret: gQUbztcirxonDLDnVfD1TfVvmUDLdf
    bucket-name: la-album-10
    url-prefix: https://la-album-10.oss-cn-shenzhen.aliyuncs.com/

server:
  port: 9090