[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-server"
version = "0.1.0"
description = "MCP Server for La-Album API Tools"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "mcp[cli]",
    "requests",
]
