name: Build and Deploy

on:
  push:
    branches: [ "b12210260" ]
  pull_request:
    branches: [ "b12210260" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: cyy1019
      FRONTEND_IMAGE: cyy1019/la-album-frontend
      BACKEND_IMAGE: cyy1019/La-Album-backend

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    # Build and push backend image
    - name: Build backend Docker image
      run: |
        cd La-Album-backend
        ./mvnw clean package -DskipTests
        docker build -t $BACKEND_IMAGE:latest .
        docker push $BACKEND_IMAGE:latest

    # Build and push frontend image
    - name: Build frontend Docker image
      run: |
        cd La-Album-frontend
        docker build -t $FRONTEND_IMAGE:latest .
        docker push $FRONTEND_IMAGE:latest