name: Build and Deploy

on:
  push:
    branches: [ "b12210260" ]
  pull_request:
    branches: [ "b12210260" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ------- Backend Build -------
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Backend with Maven
        run: |
          cd La-Album-backend
          mvn clean install -DskipTests

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: La-Album-backend/target/*.jar

      # ------- Frontend Build -------
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & Build Frontend
        run: |
          cd la-album-frontend
          npm install
          npm run build

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: la-album-frontend/dist

      # ------- Docker Build & Deploy -------
      - name: Build Docker Images
        run: |
          docker build -t album-backend -f docker/backend.Dockerfile ./La-Album-backend
          docker build -t album-frontend -f docker/frontend.Dockerfile ./la-album-frontend

      - name: Save Docker Images
        run: |
          docker save album-backend > album-backend.tar
          docker save album-frontend > album-frontend.tar

      - name: Upload Docker Images
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            album-backend.tar
            album-frontend.tar